-- 001_categories_and_rls.sql
--
-- الغرض:
--   1. إنشاء جدول categories الناقص (الكود يكتب فيه لكنه غير موجود -> HTTP 404).
--   2. تفعيل Row Level Security على كل الجداول وإغلاقها أمام الزوار.
--
-- الخلفية: النظام منشور كموقع ثابت على GitHub Pages، ومفتاح anon مرئي
-- داخل ملفات JS العامة. بدون RLS أي زائر يقدر يقرأ ويكتب ويحذف كل البيانات.
--
-- بعد تشغيل هذا الملف: الوصول محصور بالمستخدمين المسجَّلين (authenticated).
-- دور anon لا يملك أي سياسة => مرفوض تلقائياً.

begin;

-- ---------------------------------------------------------------
-- 1) جدول categories الناقص
-- ---------------------------------------------------------------
create table if not exists public.categories (
  id         bigint generated by default as identity primary key,
  name       text not null unique,
  created_at timestamptz not null default now()
);

-- التصنيفات الافتراضية التي كان الكود يستخدمها كـ fallback
insert into public.categories (name)
values ('إلكترونيات'), ('إكسسوارات'), ('شاشات')
on conflict (name) do nothing;

-- ---------------------------------------------------------------
-- 2) تفعيل RLS على كل جداول public
-- ---------------------------------------------------------------
alter table public.categories          enable row level security;
alter table public.products            enable row level security;
alter table public.purchases           enable row level security;
alter table public.sales_invoices      enable row level security;
alter table public.sales_items         enable row level security;
alter table public.expenses            enable row level security;
alter table public.maintenance_tickets enable row level security;
alter table public.damages             enable row level security;
alter table public.productions         enable row level security;
alter table public.store_settings      enable row level security;

-- ---------------------------------------------------------------
-- 3) السياسات: صلاحية كاملة للمستخدم المسجَّل فقط
--    (نظام مستخدم واحد - صاحب المحل)
-- ---------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array[
    'categories', 'products', 'purchases', 'sales_invoices', 'sales_items',
    'expenses', 'maintenance_tickets', 'damages', 'productions', 'store_settings'
  ]
  loop
    execute format('drop policy if exists authenticated_full_access on public.%I', t);
    execute format(
      'create policy authenticated_full_access on public.%I
         for all to authenticated
         using (true) with check (true)', t);
  end loop;
end $$;

commit;
